server:
  context-path: /api
---
spring:
    application:
        name: royal-rangers
    profiles:
        active: dev
    main:
        banner-mode: "off"
    jpa:
        show_sql: false
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
    mvc:
        favicon:
            enabled: false
---
spring:
    profiles: dev
    datasource:
        url: jdbc:mysql://localhost:3306/royalrangers?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password:
        test-on-borrow: true
        validation-query: SELECT 1
        test-while-idle: true
    jpa:
        hibernate:
            ddl-auto: create
    resources:
        chain:
            cache: false
---
spring:
    profiles: prod
    datasource:
        url:
        username:
        password:
        validation-query: SELECT 1
        test-while-idle: true
    jpa:
        hibernate:
            ddl-auto: create
    resources:
        chain:
            cache: true
---
jwt:
  header: Authorization
  secret: s3kr3t
  expiration: 604800
---
dropbox:
    appName: RoyalRanger
    accessToken: DFoAZto0iaAAAAAAAAAACfPm4YmwBUR7cCcP9_KsZwQLyVjOMA_1NksW30T7RXLW
    avatarPrefix: /avatar/